networks:
  national_pet_registry_network:
    driver: bridge

volumes:
  national_pet_registry_network_db_data:

services:
  postgresdb:
    image: postgres:16-bullseye
    container_name: national_pet_registry_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h localhost -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_DATABASE}",
      ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - national_pet_registry_network
    volumes:
      - national_pet_registry_network_db_data:/var/lib/postgresql/data

  app:
    container_name: national_pet_registry_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - national_pet_registry_network